const suits = [
  { key: "m", order: 0, marks: ["一萬", "二萬", "三萬", "四萬", "五萬", "六萬", "七萬", "八萬", "九萬"], tone: "red" },
  { key: "p", order: 1, marks: ["①", "②", "③", "④", "⑤", "⑥", "⑦", "⑧", "⑨"], tone: "dot" },
  { key: "s", order: 2, marks: ["1索", "2索", "3索", "4索", "5索", "6索", "7索", "8索", "9索"], tone: "green" },
];

const honors = [
  { id: "ton", mark: "東", tone: "green" },
  { id: "nan", mark: "南", tone: "green" },
  { id: "sha", mark: "西", tone: "green" },
  { id: "pei", mark: "北", tone: "green" },
  { id: "haku", mark: "白", tone: "" },
  { id: "hatsu", mark: "發", tone: "green" },
  { id: "chun", mark: "中", tone: "red" },
];

const players = ["bottom", "right", "top", "left"];
const windOrder = ["東", "南", "西", "北"];
const cpuAutoAdvanceMs = 40;
const playerLabels = {
  bottom: "Player",
  right: "下家",
  top: "対面",
  left: "上家",
};
const allTileTypes = [
  ...suits.flatMap((suit) => suit.marks.map((mark, index) => ({
    index: suit.order * 9 + index,
    order: suit.order * 100 + index,
    mark,
    tone: suit.tone,
    suit: suit.key,
    number: index + 1,
  }))),
  ...honors.map((honor, index) => ({
    index: 27 + index,
    order: 300 + index,
    mark: honor.mark,
    tone: honor.tone,
    suit: "z",
    number: index + 1,
  })),
];
const state = {
  rules: {
    gameType: "hanchan",
    seatMode: "cpu4",
    initialPoints: 25000,
    redDora: true,
    tobi: false,
    abortiveDraws: false,
    agariYame: false,
    cpuAttack: "normal",
    cpuLearning: true,
    learningMode: "fast",
    autoSelfPlay: true,
  },
  ai: {
    weights: null,
    decisions: [],
    roundDecisions: [],
    games: 0,
    gamesByType: { tonpuu: 0, hanchan: 0 },
  },
  gameStarted: false,
  wall: [],
  doraIndicator: null,
  uraDoraIndicator: null,
  hands: {},
  rivers: {},
  melds: {},
  openYakuPlans: {},
  revealedHands: {},
  scores: { bottom: 25000, right: 25000, top: 25000, left: 25000 },
  current: "bottom",
  awaitingDraw: true,
  autoTsumogiri: false,
  riichiPending: false,
  lastDiscard: null,
  callChoices: [],
  pendingCpuIndex: 0,
  cpuTimer: null,
  cpuWatchdogTimer: null,
  cpuHeartbeatTimer: null,
  cpuPumpTimer: null,
  cpuTimerStartedAt: 0,
  lastProgressKey: "",
  lastProgressAt: 0,
  autoNextGameAt: 0,
  paifuTrialNo: 0,
  currentPaifu: null,
  paifuViewer: null,
  waitDisplay: true,
  noCallMode: false,
  autoWin: false,
  ronPending: false,
  pendingRon: null,
  viewSeat: "bottom",
  gameType: "hanchan",
  currentGameType: "hanchan",
  roundWindIndex: 0,
  dealerIndex: 0,
  round: 1,
  honba: 0,
  riichiSticks: 0,
  riichi: false,
  riichiPlayers: {},
  ippatsuEligible: {},
  roundEnded: false,
  gameEnded: false,
  paused: false,
  resumeAction: null,
  pausedBeforeExitConfirm: false,
  lastWinner: null,
  drawOk: {},
  drawTimer: null,
  pendingDrawGameEnd: false,
};

const $ = (id) => document.getElementById(id);
